name: "Release"

on:
  release:
    types:
      - "published"

permissions: {}

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4.2.2"

      - name: Set VERSION variable from tag
        run: |
          TAG=${{ github.event.release.tag_name }}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: "Adjust version number"
        shell: "bash"
        run: |
          yq -i -o json '.version="${{ env.VERSION }}"' \
            "${{ github.workspace }}/custom_components/must_inverter/manifest.json"

      - name: "ZIP the integration directory"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/must_inverter"
          zip must_inverter.zip -r ./

      - name: "Upload the ZIP file to the release"
        uses: softprops/action-gh-release@v2.2.2
        with:
          files: ${{ github.workspace }}/custom_components/must_inverter/must_inverter.zip
